name: "RPI 4B Image"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest-arm
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#packages.aarch64-linux.rpi4B-iso
