name: "RPI 4B Image"
on:
  push:
    tags:
    - '*'
jobs:
  rpi4-img:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#packages.aarch64-linux.rpi4B-iso
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "result/sd-image/*"
